PROJECT:
  task: "blip2_pretrain_coco_karpathy"
  model_idx: "1"
PATH:
  train_file: '/media/workspace/linchenxi/projects/blip/coco_karpathy_train.json'
  val_file: '/media/workspace/linchenxi/projects/blip/coco_karpathy_val.json'
  data_root: '/media/workspace/linchenxi/projects/blip/'
  model_dir: "/NAS3/Members/linchenxi/blip/model"
MODEl:
  optimization:
      image_size: 224
      batch_size: 75
      queue_size: 57600
      alpha: 0.4
      optimizer: "AdamW"
      scheduler: null
      base_lr: 5e-5
      weight_decay: 0.05
      epoch: 20
      total_steps_ratio: 0.2
      warmup_steps_ratio: 0.01
      num_train_samples: 2000
      num_vali_samples: 1000



